# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
comment: false
ignore:
  - "tests"
  - "lib/BackgroundJob/ContextChat"
  - "lib/ContextChat"
  - "lib/Db/ContextChat"
  - "lib/Migration/Version5200Date20250728000000.php"
  - "lib/Service/ContextChat"
  - "lib/Vendor"
